name: "Set Project Closed Date"

on:
  issues:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: read
  issues: read

jobs:
  orchestrate:
    uses: ./.github/workflows/reuseable-set-project-closed-date.yml
    secrets:
      project_pat: ${{ secrets.ORG_PROJECT_PAT }}
    with:
      project_url: "https://github.com/orgs/blinklabs-io/projects/11"
      closed_date_field: "Closed Date"
      closed_at: "${{ github.event.issue.closed_at }}"
